server:
  port: 8095

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://192.168.18.5:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: rbenitez-accounts-service
          uri: lb://rbenitez-accounts-service
          predicates:
            - Path=/accounts/**
        - id: rbenitez-consulting-service
          uri: lb://rbenitez-consulting-service
          predicates:
            - Path=/consulting/**
        - id: rbenitez-credits-service
          uri: lb://rbenitez-credits-service
          predicates:
            - Path=/credits/**
        - id: rbenitez-customer-service
          uri: lb://RBENITEZ-CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
        - id: rbenitez-transaction-service
          uri: lb://rbenitez-transaction-service
          predicates:
            - Path=/transaction/**